# PostgreSQL DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:travel_agency}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:travel_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:travel_pass}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
logging.level.org.hibernate.orm.jdbc.warn=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
spring.jackson.deserialization.fail-on-unknown-properties=true

# Async
app.async.confirmation-delay-ms=15000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true