# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_agency
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
logging.level.org.hibernate.orm.jdbc.warn=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
spring.jackson.deserialization.fail-on-unknown-properties=true